version: '3'

services:
  backend-app:
    image: myapp:v1
    restart: on-failure
    depends_on:
      - mysql_db
    ports:
      - '8080:8080'
    environment:    #TO-DO: Get env variables from the host machine
      - DATABASE_HOST=mysql_db
      - DATABASE_USER=${MYSQLDB_USER}
      - DATABASE_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DATABASE_NAME=${MYSQLDB_DATABASE}
      - DATABASE_PORT=${MYSQLDB_LOCAL_PORT}

  mysql_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=khalil
      - MYSQL_DATABASE=education
    ports:
      - '3306:3306'
    volumes:
      - education-project-volume:/var/lib/mysql
volumes:
  education-project-volume:
    driver: local


